# ❤️ Поддержка проекта GSDiscord

Спасибо за интерес к поддержке нашего проекта! Ваша поддержка помогает нам продолжать разработку и улучшение GSDiscord.

## 🌟 Способы поддержки

### 🆓 Бесплатные способы:
- ⭐ **Поставьте звездочку** на GitHub
- 🐛 **Сообщайте об ошибках** через Issues
- 💡 **Предлагайте новые функции**
- 📖 **Улучшайте документацию**
- 🔄 **Делитесь проектом** с друзьями и коллегами

### 💝 Финансовая поддержка:
- ☕ [Buy me a coffee](https://www.buymeacoffee.com/izenapp)
- 💳 [GitHub Sponsors](https://github.com/sponsors/IZenApp)
- 🎯 [PayPal](https://paypal.me/izenapp)

## 🚀 Как помочь с разработкой

1. **Fork** репозиторий
2. **Создайте** ветку для новой функции (`git checkout -b feature/amazing-feature`)
3. **Commit** ваши изменения (`git commit -m 'Add some amazing feature'`)
4. **Push** в ветку (`git push origin feature/amazing-feature`)
5. **Откройте** Pull Request

## 🎯 Приоритетные задачи

- [ ] Добавление поддержки множественных Google Sheets
- [ ] Веб-интерфейс для управления ботом
- [ ] Поддержка Telegram уведомлений
- [ ] Система плагинов
- [ ] Docker контейнеризация

## 📞 Связь

- **Email:** support@izenapp.com
- **Discord:** [Наш сервер](https://discord.gg/your-server)
- **Telegram:** [@izenapp](https://t.me/izenapp)

---

**🙏 Каждый вклад ценен и важен для развития проекта!**
